set special CFLAGS

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -57,6 +57,62 @@ parts:
     organize:
       '*.tar.gz': etc/
 
+  # wine-apt:  # installs most recent devel version
+  #   plugin: nil
+  #   build-packages: [wget]
+  #   override-stage: |
+  #     dpkg --add-architecture i386
+  #     mkdir -pm755 /etc/apt/keyrings
+  #     wget -qO /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
+  #     wget -qNP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources
+  #     apt-get update
+  #     apt-get -y install --install-recommends winehq-devel
+  #     craftctl default
+
+  # wine-appimage:
+  #   # This is tricky b/c the included libs are different from those in other
+  #   # parts, so binaries from different parts seem to have trouble working.
+  #   source: .  # "Failed to pull source" when URL is given here
+  #   plugin: dump
+  #   source-type: local
+  #   build-packages:
+  #     - wget
+  #     - rsync
+  #   override-pull: |
+  #     file=wine-devel_9.19-x86_64.AppImage
+  #     wget -q https://github.com/FaithLife-Community/wine-appimages/releases/download/9.19-devel/$file
+  #     if [[ ! -r $file ]]; then
+  #       exit 1
+  #     fi
+  #     chmod +x $file
+  #     ./$file --appimage-extract >/dev/null
+  #     if [[ ! -d squashfs-root ]]; then
+  #       exit 1
+  #     fi
+  #     rm -f $file
+  #     # Fix file permissions.
+  #     chmod -R go+rX .  # https://forum.snapcraft.io/t/openaudible-bounty/16835/5
+  #   stage:
+  #     - -lib/libselinux.so*
+  #   #   - -AppRun*
+  #   #   - -.bundle.yml
+  #   #   - -.DirIcon
+  #   #   - -*.desktop
+  #   #   - -*.svg
+  #   #   - -winedata
+  #   #   - -wrapper
+  #   organize:
+  #     'squashfs-root/bin/winetricks': bin/winetricks
+  #     'squashfs-root/lib/*': lib
+  #     'squashfs-root/lib64/*': lib64
+  #     'squashfs-root/opt/*': opt
+  #   # stage-packages:  # when pkg-config runs it can lead to OOM error on my VPS
+  #   #   - libcapi20-dev  # libcapi20.so.3
+  #   #   - libgphoto2-dev  # libgphoto2.so.6, libgphoto2_port.so.12, 
+  #   #   - ocl-icd-opencl-dev  # libOpenCL.so.1
+  #   #   - libsane-dev  # libsane.so.1
+  #   #   - libusb-1.0-0-dev  # libusb-1.0.so.0
+
   wine-prep:
     # This saves having to repeat [64-bit] build-packages for each wine* part.
     # Also, build-packages from all parts are installed prior to the completion
@@ -124,62 +180,6 @@ parts:
       - flex 
       - bison
       - gcc-multilib
-
-  # wine-apt:  # installs most recent devel version
-  #   plugin: nil
-  #   build-packages: [wget]
-  #   override-stage: |
-  #     dpkg --add-architecture i386
-  #     mkdir -pm755 /etc/apt/keyrings
-  #     wget -qO /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
-  #     wget -qNP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources
-  #     apt-get update
-  #     apt-get -y install --install-recommends winehq-devel
-  #     craftctl default
-
-  # wine-appimage:
-  #   # This is tricky b/c the included libs are different from those in other
-  #   # parts, so binaries from different parts seem to have trouble working.
-  #   source: .  # "Failed to pull source" when URL is given here
-  #   plugin: dump
-  #   source-type: local
-  #   build-packages:
-  #     - wget
-  #     - rsync
-  #   override-pull: |
-  #     file=wine-devel_9.19-x86_64.AppImage
-  #     wget -q https://github.com/FaithLife-Community/wine-appimages/releases/download/9.19-devel/$file
-  #     if [[ ! -r $file ]]; then
-  #       exit 1
-  #     fi
-  #     chmod +x $file
-  #     ./$file --appimage-extract >/dev/null
-  #     if [[ ! -d squashfs-root ]]; then
-  #       exit 1
-  #     fi
-  #     rm -f $file
-  #     # Fix file permissions.
-  #     chmod -R go+rX .  # https://forum.snapcraft.io/t/openaudible-bounty/16835/5
-  #   stage:
-  #     - -lib/libselinux.so*
-  #   #   - -AppRun*
-  #   #   - -.bundle.yml
-  #   #   - -.DirIcon
-  #   #   - -*.desktop
-  #   #   - -*.svg
-  #   #   - -winedata
-  #   #   - -wrapper
-  #   organize:
-  #     'squashfs-root/bin/winetricks': bin/winetricks
-  #     'squashfs-root/lib/*': lib
-  #     'squashfs-root/lib64/*': lib64
-  #     'squashfs-root/opt/*': opt
-  #   # stage-packages:  # when pkg-config runs it can lead to OOM error on my VPS
-  #   #   - libcapi20-dev  # libcapi20.so.3
-  #   #   - libgphoto2-dev  # libgphoto2.so.6, libgphoto2_port.so.12, 
-  #   #   - ocl-icd-opencl-dev  # libOpenCL.so.1
-  #   #   - libsane-dev  # libsane.so.1
-  #   #   - libusb-1.0-0-dev  # libusb-1.0.so.0
 
   wine64:
     # https://github.com/mmtrt/Wine-Builds/blob/master/build_wine.sh
@@ -264,20 +264,22 @@ parts:
       - CROSSCC_X64: "x86_64-w64-mingw32-gcc"
       - CROSSCXX_X64: "x86_64-w64-mingw32-g++"
       - CFLAGS_X32: "-march=i686 -msse2 -mfpmath=sse -O2 -ftree-vectorize"
+      - CFLAGS_X32: "-msse2 -mfpmath=sse -O2 -ftree-vectorize"  # oudedetai
       - CFLAGS_X64: "-march=x86-64 -msse3 -mfpmath=sse -O2 -ftree-vectorize"
+      - CFLAGS_X64: "-msse3 -mfpmath=sse -O2 -ftree-vectorize"  # oudedetai
       - CROSSCFLAGS_X32: "${CFLAGS_X32}"
       - CROSSCFLAGS_X64: "${CFLAGS_X64}"
       # needed for build
       - PKG_CONFIG_LIBDIR: /usr/lib/i386-linux-gnu/pkgconfig:/usr/local/lib/pkgconfig:/usr/local/lib/i386-linux-gnu/pkgconfig
       # - CC: "gcc-9"  cc1: error: CPU you selected does not support x86-64 instruction set
-      - CFLAGS: "-O2 -ftree-vectorize"  #"${CFLAGS_X32}"
+      - CFLAGS: "${CFLAGS_X32}"
       # - CXX: "g++"  #"g++-9"
       - CXXFLAGS: "${CFLAGS_X32}"
       - LDFLAGS: "-Wl,-O1,--sort-common,--as-needed"
       - CROSSLDFLAGS: "${LDFLAGS}"
-      # - CROSSCC: "${CROSSCC_X32}"  # not used, CC used instead?
-      - CROSSCFLAGS: "-O2 -ftree-vectorize"  #"${CROSSCFLAGS_X32}"
-      - CROSSCXX: "${CROSSCXX_X32}"  # not used, CCX used instead?
+      - CROSSCC: "${CROSSCC_X32}"
+      - CROSSCFLAGS: "${CROSSCFLAGS_X32}"
+      - CROSSCXX: "${CROSSCXX_X32}"
       - CROSSCXXFLAGS: "${CROSSCFLAGS_X32}"  # not used?
 
   wine32:
