handle ICU files

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -53,21 +53,60 @@ parts:
 
   icu:
     source: https://github.com/FaithLife-Community/icu/releases/download/72.1-custom%2B4/icu-win.tar.gz
-    plugin: dump
-    organize:
-      '*': etc/
-
-  wine:
     plugin: nil
-    build-packages: [wget]
-    override-stage: |
-      dpkg --add-architecture i386
-      mkdir -pm755 /etc/apt/keyrings
-      wget -qO /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
-      wget -qNP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources
-      apt-get update
-      apt-get -y install --install-recommends winehq-devel
-      craftctl default
+    organize:
+      '*.tar.gz': etc/
+
+  # wine:
+  #   plugin: nil
+  #   build-packages: [wget]
+  #   override-stage: |
+  #     dpkg --add-architecture i386
+  #     mkdir -pm755 /etc/apt/keyrings
+  #     wget -qO /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
+  #     wget -qNP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources
+  #     apt-get update
+  #     apt-get -y install --install-recommends winehq-devel
+  #     craftctl default
+
+  # This is tricky b/c the folder structure seems non-standard, so other parts
+  # may have trouble working correctly with wine.
+  wine-appimage:
+    source: .  # "Failed to pull source" when URL is given here
+    plugin: dump
+    source-type: local
+    build-packages:
+      - wget
+    override-pull: |
+      file=wine-devel_9.19-x86_64.AppImage
+      wget -q https://github.com/FaithLife-Community/wine-appimages/releases/download/9.19-devel/$file
+      if [[ ! -r $file ]]; then
+        exit 1
+      fi
+      chmod +x $file
+      ./$file --appimage-extract >/dev/null
+      if [[ ! -d squashfs-root ]]; then
+        exit 1
+      fi
+      rm -f $file
+      # Fix file permissions.
+      chmod -R go+rX .  # https://forum.snapcraft.io/t/openaudible-bounty/16835/5
+    stage:
+      - -AppRun*
+      - -.bundle.yml
+      - -.DirIcon
+      - -*.desktop
+      - -*.svg
+      - -winedata
+      - -wrapper
+    organize:
+      'squashfs-root/*': .
+    # stage-packages:  # when pkg-config runs it can lead to OOM error on my VPS
+    #   - libcapi20-dev  # libcapi20.so.3
+    #   - libgphoto2-dev  # libgphoto2.so.6, libgphoto2_port.so.12, 
+    #   - ocl-icd-opencl-dev  # libOpenCL.so.1
+    #   - libsane-dev  # libsane.so.1
+    #   - libusb-1.0-0-dev  # libusb-1.0.so.0
 
   # # REF:
   # # https://github.com/mmtrt/Wine-Builds/blob/master/build_wine.sh
@@ -152,43 +191,6 @@ parts:
   #   source: https://gitlab.winehq.org/wine/wine.git
   #   source-tag: wine-9.19
   #   source-depth: 1
-
-  # wine-appimage:
-  #   source: .  # "Failed to pull source" when URL is given here
-  #   plugin: dump
-  #   source-type: local
-  #   build-packages:
-  #     - wget
-  #   override-pull: |
-  #     file=wine-devel_9.19-x86_64.AppImage
-  #     wget -q https://github.com/FaithLife-Community/wine-appimages/releases/download/9.19-devel/$file
-  #     if [[ ! -r $file ]]; then
-  #       exit 1
-  #     fi
-  #     chmod +x $file
-  #     ./$file --appimage-extract >/dev/null
-  #     if [[ ! -d squashfs-root ]]; then
-  #       exit 1
-  #     fi
-  #     rm -f $file
-  #     # Fix file permissions.
-  #     chmod -R go+rX .  # https://forum.snapcraft.io/t/openaudible-bounty/16835/5
-  #   stage:
-  #     - -AppRun*
-  #     - -.bundle.yml
-  #     - -.DirIcon
-  #     - -*.desktop
-  #     - -*.svg
-  #     - -winedata
-  #     - -wrapper
-  #   organize:
-  #     'squashfs-root/*': .
-  #   # stage-packages:  # when pkg-config runs it can lead to OOM error on my VPS
-  #   #   - libcapi20-dev  # libcapi20.so.3
-  #   #   - libgphoto2-dev  # libgphoto2.so.6, libgphoto2_port.so.12, 
-  #   #   - ocl-icd-opencl-dev  # libOpenCL.so.1
-  #   #   - libsane-dev  # libsane.so.1
-  #   #   - libusb-1.0-0-dev  # libusb-1.0.so.0
 
   oudedetai:
     ## just for testing
