re-add wine part

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -53,42 +53,41 @@ parts:
     organize:
       '*': etc/
 
-  # wine:
-  #   source: .  # "Failed to pull source" when URL is given here
-  #   plugin: dump
-  #   source-type: local
-  #   build-packages:
-  #     - wget
-  #   override-pull: |
-  #     file=wine-devel_9.19-x86_64.AppImage
-  #     wget -q https://github.com/FaithLife-Community/wine-appimages/releases/download/9.19-devel/$file
-  #     if [[ ! -r $file ]]; then
-  #       exit 1
-  #     fi
-  #     chmod +x $file
-  #     ./$file --appimage-extract >/dev/null
-  #     if [[ ! -d squashfs-root ]]; then
-  #       exit 1
-  #     fi
-  #     rm -f $file
-  #   override-build: |
-  #     cp --archive --link --no-dereference squashfs-root/* $CRAFT_PART_INSTALL
-  #   stage:
-  #     - -AppRun*
-  #     - -.bundle.yml
-  #     - -.DirIcon
-  #     - -*.desktop
-  #     - -*.svg
-  #     - -lib64
-  #     - -winedata
-  #     - -wrapper
-  #   # stage-packages:  # when pkg-config runs it can lead to OOM error on my VPS
-  #   #   - libcapi20-dev  # libcapi20.so.3
-  #   #   - libgphoto2-dev  # libgphoto2.so.6, libgphoto2_port.so.12, 
-  #   #   - ocl-icd-opencl-dev  # libOpenCL.so.1
-  #   #   - libsane-dev  # libsane.so.1
-  #   #   - libusb-1.0-0-dev  # libusb-1.0.so.0
-
+  wine:
+    source: .  # "Failed to pull source" when URL is given here
+    plugin: dump
+    source-type: local
+    build-packages:
+      - wget
+    override-pull: |
+      file=wine-devel_9.19-x86_64.AppImage
+      wget -q https://github.com/FaithLife-Community/wine-appimages/releases/download/9.19-devel/$file
+      if [[ ! -r $file ]]; then
+        exit 1
+      fi
+      chmod +x $file
+      ./$file --appimage-extract >/dev/null
+      if [[ ! -d squashfs-root ]]; then
+        exit 1
+      fi
+      rm -f $file
+    override-build: |
+      cp --archive --link --no-dereference squashfs-root/* $CRAFT_PART_INSTALL
+    stage:
+      - -AppRun*
+      - -.bundle.yml
+      - -.DirIcon
+      - -*.desktop
+      - -*.svg
+      - -lib64
+      - -winedata
+      - -wrapper
+    # stage-packages:  # when pkg-config runs it can lead to OOM error on my VPS
+    #   - libcapi20-dev  # libcapi20.so.3
+    #   - libgphoto2-dev  # libgphoto2.so.6, libgphoto2_port.so.12, 
+    #   - ocl-icd-opencl-dev  # libOpenCL.so.1
+    #   - libsane-dev  # libsane.so.1
+    #   - libusb-1.0-0-dev  # libusb-1.0.so.0
 
   oudedetai:
     ## just for testing
@@ -103,8 +102,8 @@ parts:
     stage-packages:
       - libncurses6
       - libncursesw6
-      - libproxy1v5
-      - glib-networking
+      # - libproxy1v5  # doesn't fix libpxbackend-1.0.so: cannot open shared object file: No such file or directory
+      # - glib-networking  # doesn't fix Failed to load module: /home/nate/snap/oudedetai/common/.cache/gio-modules/libgiolibproxy.so
       - python3-tk
     override-prime: |
       echo '<TODO>'
